# Generated by Django 3.0.5 on 2020-05-03 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('change', models.CharField(max_length=200)),
                ('percent_change', models.CharField(max_length=200)),
                ('market_caps', models.CharField(blank=True, max_length=200)),
                ('avg_volume', models.CharField(blank=True, max_length=200)),
                ('volume', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
